### ISSUE TITLE
getting exception  Caused by: java.net.BindException: Address not available 	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_212] 	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_212] 	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_212]

### ISSUE THREAD

**Issue by PrachipriyaPrasad** [SpringWebSocket/facebook-feed-socketio#1]
when i 'm running my code with in spring boot its working fine but when i run same code in docker its showing error . 
I'm providing my system IP address as host number and port is 3000 

Caused by: java.net.BindException: Address not available
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_212]
	at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_212]
	at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_212]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_212]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515) ~[netty-transport-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.39.Final.jar!/:4.1.39.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]

**Comment by awesomefua** [comment]
Hello @PrachipriyaPrasad How did you resolve this as I have a similar issue
